### ISSUE TITLE
Ask @weppos nicely for 'whois'

### ISSUE THREAD

**Issue by mikemaccana** [hjr265/node-whois#21]
The current `whois` package on npm was last updated 3 years ago, is version 0.0.0, described by the author @weppos as:

    My attempt to build a JavaScript WHOIS client for node.js.
    Please note this is just an experiment! 

Since `node-whois` has 10x+ the downloads, an a lot more updates, having it use the name 'whois' (and not include node- per the [npm guidelines](https://docs.npmjs.com/files/package.json) ) would be good.

If the node-whois people are amenable, maybe asking @weppos if he could [transfer ownership](https://docs.npmjs.com/cli/owner) of whois would steer users towards this popular, maintained package.

**Comment by hjr265** [comment]
@mikemaccana Thanks for bringing this up. I have made an attempt to get in touch with @weppos via email. Waiting for his response.

**Comment by weppos** [comment]
@hjr265 @mikemaccana sorry for the late reply. I agree at the condition you'll do the same in the future if you will ever stop maintaining this lib. See weppos/whois.js#1

Please just give me some days to read the docs.

**Comment by hjr265** [comment]
The package has been renamed and a deprecation warning has been added for the old entry in the registry.
