### ISSUE TITLE
Ability to merge servers with own list

### ISSUE THREAD

**Issue by likerRr** [hjr265/node-whois#22]
Hello! 

It would be great to have ability to merge own `servers.json` (or an object) list with existing. For example I know some whois servers, that better match my requirements and existing `server` options don't allow to do it for me :disappointed:

**Comment by hjr265** [comment]
Hi,

I see what you mean. I am thinking of exporting the `SERVER` variable. It's a simple change, and that should allow you to change the object as necessary before using the `lookup` function.

**Comment by likerRr** [comment]
Thank you :+1:
