### ISSUE TITLE
Does not support .space

### ISSUE THREAD

**Issue by TimeTravelersHackMe** [hjr265/node-whois#23]
Does not support .space lookups. Also, any ideas on how I can derive all the registerable domain extensions from the servers.json file.

PS Thanks for this NPM!

**Comment by hjr265** [comment]
@TimeTravelersHackMe The package now supports .space. 

Regarding which TLDs are available for registering domains on, it probably depends on many factors (for example some TLDs require you to have an establishment of some sort in their respective countries. If I am not missing something, a list will need to be compiled somewhat manually for that (if one doesn't already exist).
