### ISSUE TITLE
Doesn't support .info domains

### ISSUE THREAD

**Issue by Biomorphix** [hjr265/node-whois#25]
Please add support to .info domains, I tried to lookup "get.info", but nothing happens. It will be VERY cool, if node-whois will have parser too. Thx.

**Comment by Biomorphix** [comment]
I've found a problem: there is two whois servers in servers.json, plus one of them don't work - "whois.nic.info". I've deleted it and left only:  

    "info": "whois.afilias.net"

**Comment by hjr265** [comment]
@Biomorphix If I recall right this was fixed recently by a contributor through a pull request #24 

Can you please confirm if you are using the latest version?

**Comment by Biomorphix** [comment]
@hjr265 
Oh, it's my fault - my version is "2.1.3".

**Comment by hjr265** [comment]
@Biomorphix No problem :)

Closing the issue.
