### ISSUE TITLE
Incorrect results for IDN .de domains

### ISSUE THREAD

**Issue by frdmn** [hjr265/node-whois#26]
When looking up an IDN .de domain, node-whois is trying to convert it into punyname before sending the actual whois request:

```js
"data": "Domain: xn--kche-0ra.de\nStatus: invalid\n",
"server": {
    "host": "whois.denic.de",
    "port": 43,
    "query": "$addr\r\n"
}
```

DENIC's whois server (`whois.denic.de`) however expects the domain in the normal unicode format:

```js
"data": "Domain: küche.de\nDomain-Ace: xn--kche-0ra.de\nStatus: connect\n",
"server": {
    "host": "whois.denic.de",
    "port": 43,
    "query": "$addr\r\n"
}
```

For the result above I changed the following code:

```diff
-      return socket.write(server.query.replace('$addr', punycode.toASCII(addr)));
+      return socket.write(server.query.replace('$addr', addr));
```

I have no clue if this is a special case or if it's the general way to lookup IDN domains in whois servers. Can anyone shed some light in here?

**Comment by hjr265** [comment]
Hi @frdmn .. I think we may need to selectively disable the use of punycode for some of these WHOIS servers. And then add an option to skip punycode conversation during invocation. Apparently some servers can handle unicode now.

**Comment by frdmn** [comment]
I totally agree with the conclusion! 👍

**Comment by frdmn** [comment]
Thanks a lot, Mahmud!

**Comment by hjr265** [comment]
@frdmn No problem at all!

**Comment by frdmn** [comment]
@hjr265 Would you mind bumping the NPM package to 2.1.6 so I can make use of the latest additions? :)

**Comment by hjr265** [comment]
@frdmn Done :)
