### ISSUE TITLE
PendingDelete Domain, Redemption, etc

### ISSUE THREAD

**Issue by willihangga** [hjr265/node-whois#27]
I think there's a bug when whois lookup trying to get information from PendingDelete domain, Redemption domain, etc. There is an example:
WHOIS: https://cloudup.com/cVAZ-TbLLRl (no match, mean available)
WHO.IS/whois: https://cloudup.com/c6G1FEp57ZP (pendingdelete, mean taken)
Is there any solution?

**Comment by willihangga** [comment]
After trying into NPM with verbose mode, I've got the valid data: https://cloudup.com/cnuCBS9Pgac
code: https://tonicdev.com/57395712f54449110058d509/5739588ca492941100e07f5e

**Comment by hjr265** [comment]
Hi @willihangga 

Thanks for reporting this. I will look into it asap.

**Comment by hjr265** [comment]
So, node-whois attempts to follow redirection as long as it finds something that matches this regular expression in the response:

```
(ReferralServer|Registrar Whois|Whois Server):\s*(r?whois:\/\/)?(.+)
```

It seems when domains are deleted, the redirection takes node-whois to a WHOIS server where it doesn't serve any data for the domain (which makes sense, as the domain is being deleted).

What we can do is determine if the domain is about to be deleted and interrupt the  redirection. But I will have to take a look at this and see if we can do it reliably. Even then I am not 100% convinced that we should handle this within the package as users of the package can always use the verbose mode to get all intermediate WHOIS data.

**Comment by willihangga** [comment]
when I use `whois.verisign-grs.com` (https://cloudup.com/czju5TF1Lwp) as default host server, is there any request limit? cause I need about 35-40K request every single day

**Comment by hjr265** [comment]
I am not sure if there is any reliable source for that information: http://serverfault.com/questions/359179/what-is-the-limit-of-queries-on-whois-servers

**Comment by willihangga** [comment]
Okay, I think I'm going to get another way around, thanks for your answer, awesome work!
