### ISSUE TITLE
Close connection on timeout

### ISSUE THREAD

**Issue by schnittstabil** [hjr265/node-whois#33]
If a timeout occurs, the socket remains open. That's bad for CLI scripts, because they don't exit until all sockets are closed.

According to the [socket.setTimeout(timeout[, callback]) docs](https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback):

> When an idle timeout is triggered the socket will receive a 'timeout' event but the connection will not be severed. The user must manually `end()` or `destroy()` the socket.

I therefore suggest to `destroy()` the socket (`end()` leads to `write` after `end` errors in some cases):
```diff
 	socket.on 'timeout', =>
+		socket.destroy
 		done new Error 'lookup: timeout'
```

**Comment by hjr265** [comment]
@schnittstabil Thanks, I will add `socket.destroy()`.
